### ISSUE TITLE
when i was trying to make a 1.14.4 pack

### ISSUE THREAD

**Issue by cmspeedau** [SKCraft/Launcher#337] opened 2020-02-20 01:16 UTC
java.io.IOException: Did not get expected response code, got 403 for https://s3.amazonaws.com/Minecraft.Download/versions/1.14.4/1.14.4.json
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
	at com.skcraft.launcher.builder.PackageBuilder.readVersionManifest(PackageBuilder.java:309)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:381)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by spannerman79** [comment] 2020-02-20 02:14
Duplicate of https://github.com/SKCraft/Launcher/issues/235

**Closed** 2020-12-24 18:51 UTC
Labels: fixed
