### ISSUE TITLE
403 all over the Place

### ISSUE THREAD

**Issue by steevLP** [SKCraft/Launcher#317] opened 2019-08-07 02:45 UTC
I got everything to work it compiled and runs. So the next thing would be obviusly to make my own modpack. but it resutls in this crashlog

[information] 
[information] --- Reading version manifest... ---
[information] Fetching version manifest from https://s3.amazonaws.com/Minecraft.Download/versions/1.0.0/1.0.0.json...
[warnung] Task failed
java.io.IOException: Did not get expected response code, got 403 for https://s3.amazonaws.com/Minecraft.Download/versions/1.0.0/1.0.0.json
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
	at com.skcraft.launcher.builder.PackageBuilder.readVersionManifest(PackageBuilder.java:309)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:381)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

is there anything i am doing wrong here? and if yes how do i fix it?

**Comment by spannerman79** [comment] 2019-08-07 02:46
Duplicate of #235

**Closed** 2019-08-07 03:03 UTC
