### ISSUE TITLE
[1.15.2] Forge won't install

### ISSUE THREAD

**Issue by Akulav** [SKCraft/Launcher#339] opened 2020-03-15 23:27 UTC
[info] --- Checking for mod loaders to install... ---
[info] Installing forge-1.15.2-31.1.0-installer.jar...
[warning] Task failed
java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:160)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:126)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:393)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

It is looking for an "install" section inside the install_profile from inside the installer. Tried to do a workaround but always leads to other problems. Should be easy to fix. Help.

**Comment by spannerman79** [comment] 2020-03-16 04:09
Duplicate of https://github.com/SKCraft/Launcher/issues/235

**Comment by H4Mm3r** [comment] 2020-04-12 12:03
This issue is not about Mojang' changes but Forge's one. It's still crashing after moving to the new librairies urls.

[infos] --- Checking for mod loaders to install... ---
[infos] Installing forge-1.14.4-28.2.3-installer.jar...
[avertissement] Task failed
java.lang.NullPointerException
	at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:162)
	at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:128)
	at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:392)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
	at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Closed** 2020-12-24 18:51 UTC
Labels: fixed
