### ISSUE TITLE
Fancy launcher font issue

### ISSUE THREAD

**Issue by TheBiemGamer** [SKCraft/Launcher#435] opened 2021-08-11 09:51 UTC
When I build the fancy launcher the font is very pixelated when compared to the old version how can I fix this?

New version screenshot: 
![image](https://user-images.githubusercontent.com/47662596/129008306-2fa26d72-25f2-4952-9daa-eae75e53d5a1.png)

Old version screenshot:
![image](https://user-images.githubusercontent.com/47662596/129008602-3d1e146b-4cef-4b12-a949-6195769571ad.png)

And I can't use the old version because that one can't login to minecraft anymore since they started moving accounts to microsoft

**Comment by hedgehog1029** [comment] 2021-08-11 16:08
duplicate of #390, Substance was updated to work with newer Javas and it seems to have broken text antialiasing for some reason. track #390 for updates :)

**Closed by hedgehog1029** 2021-08-11 16:08 UTC
