### ISSUE TITLE
Problem with charset: Cyrillic / Russian symbols

### ISSUE THREAD

**Issue by MJRamon** [SKCraft/Launcher#123] opened 2016-01-14 17:11 UTC
Hello! Despite my efforts, it didn't work.

Here is how text should be visible:
features.intro=Выберите дополнительные возможности для установки.

Our native charset is windows-1251. It also should work in UTF-8.

Here How it is shown in ISO-8859-1 and UTF-8 (with and without BOM)::
features.intro=ÐÑÐ±ÐµÑÐ¸ÑÐµ Ð´Ð¾Ð¿Ð¾Ð»Ð½Ð¸ÑÐµÐ»ÑÐ½ÑÐµ Ð²Ð¾Ð·Ð¼Ð¾Ð¶Ð½Ð¾ÑÑÐ¸ Ð´Ð»Ñ ÑÑÑÐ°Ð½Ð¾Ð²ÐºÐ¸.

I tried windows-1251, no such luck also. Please, add support for cyrillic symbols, thank you!

**Comment by MJRamon** [comment] 2016-01-14 23:03
Actually, I was suprised, that it's not in UTF-8. Current ISO-8859-1 limits localization SIGNIFICANTLY. Please, transfer to UTF-8, because there is no way to translate launcher to my language now.

**Comment by SSVsSunSt** [comment] 2016-01-15 17:24
Same problem here!

**Comment by sk89q** [comment] 2016-01-16 03:28
duplicate of #95

I'll be looking into it.

**Closed by sk89q** 2016-01-16 03:28 UTC
