### ISSUE TITLE
build.bat doesn't work

### ISSUE THREAD

**Issue by ghost** [SKCraft/Launcher#246] opened 2018-07-27 22:06 UTC
Some input file use or override a deprecated API

**Comment by sk89q** [comment] 2018-07-30 01:40
Need a log

**Comment by ElementKZ** [comment] 2018-07-31 12:00
https://pastebin.com/nPaB2UrN

**Comment by spannerman79** [comment] 2019-04-27 03:52
`1.6 is obsolete and will be removed in a future  ` is referring to https://github.com/SKCraft/Launcher/blob/master/build.gradle#L32...#L33

Can be ignored.

**Comment by Aughen** [comment] 2019-10-02 17:11
I am assuming this is the same issue? is there a work arround? 

_Output files will be in [subproject]/build/libs
*******************************************


Task :launcher:compileJava FAILED
warning: [options] bootstrap class path not set in conjunction with -source 1.6
B:\Launcher\Launcher-master - 1.13 fixed\launcher\src\main\java\com\skcraft\launcher\model\minecraft\Downloads.java:1: error: class, interface, or enum expected
ackage com.skcraft.launcher.model.minecraft;

B:\Launcher\Launcher-master - 1.13 fixed\launcher\src\main\java\com\skcraft\launcher\model\minecraft\VersionManifest.java:38: error: <identifier> expected
JsonIgnore

B:\Launcher\Launcher-master - 1.13 fixed\launcher\src\main\java\com\skcraft\launcher\model\modpack\LatestVersions.java:1: error: class, interface, or enum expected
LatestVersions.java package com.skcraft.launcher.model.modpack;

B:\Launcher\Launcher-master - 1.13 fixed\launcher\src\main\java\com\skcraft\launcher\model\modpack\ModpackVersion.java:1: error: class, interface, or enum expected
ModpackVersion.javapackage com.skcraft.launcher.model.modpack;

4 errors
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:compileJava'.
 Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
6 actionable tasks: 2 executed, 4 up-to-date
Press any key to continue . . .

**Comment by spannerman79** [comment] 2019-10-02 17:14
Duplicate of #235 (and various others related)

**Closed** 2020-12-26 15:43 UTC
Labels: question
