### ISSUE TITLE
[HELP] java.io.IOException: 3 file(s) could not be downloaded

### ISSUE THREAD

**Issue by enzomtpYT** [SKCraft/Launcher#310] opened 2019-07-03 21:09 UTC
To report this error, please provide:

java.io.IOException: 3 file(s) could not be downloaded
	at com.skcraft.launcher.install.HttpDownloader.execute(HttpDownloader.java:139)
	at com.skcraft.launcher.install.Installer.download(Installer.java:46)
	at com.skcraft.launcher.update.Updater.update(Updater.java:178)
	at com.skcraft.launcher.update.Updater.call(Updater.java:95)
	at com.skcraft.launcher.update.Updater.call(Updater.java:38)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by spannerman79** [comment] 2019-07-03 21:11
Duplicate of https://github.com/SKCraft/Launcher/issues/235

**Comment by enzomtpYT** [comment] 2019-07-03 21:14
> Duplicate of #235

i dont understand (sorry im french !)

**Comment by enzomtpYT** [comment] 2019-07-03 21:18
> Duplicata de [# 235](https://github.com/SKCraft/Launcher/issues/235)

and its in 1.12.2

**Comment by hedgehog1029** [comment] 2020-12-24 21:41
Duplicate; also fixed.

**Closed by hedgehog1029** 2020-12-24 21:41 UTC
