### ISSUE TITLE
Couldn't download modpacks?

### ISSUE THREAD

**Issue by JustStanix** [SKCraft/Launcher#313] opened 2019-07-21 03:07 UTC
Here is the error.
```
To report this error, please provide:

java.io.IOException: The list of modpacks could not be downloaded.
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:191)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:102)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Did not get expected response code, got 301 for http://turtlenetwork.net/launcher/packages.php
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
	at com.skcraft.launcher.InstanceList$Enumerator.call(InstanceList.java:139)
	... 5 more

```
I did everything exactly like in the wiki and followed every step but this keeps happening!

**Comment by spannerman79** [comment] 2019-07-21 03:48
`Caused by: java.io.IOException: Did not get expected response code, got 301`
https://httpstatuses.com/301

Needs to be a direct url - not a redirect.

**Comment by JustStanix** [comment] 2019-07-21 12:07
I see. It was http instead of https so it kept redirecting it.
Thanks!

**Comment by spannerman79** [comment] 2019-07-21 12:12
...if the issue is resolved then close the issue @JustStanix

**Closed** 2019-07-21 12:13 UTC
